name: Jekyll site CI
fn main(https://calbearox.github.io/potential-money/) {
    println!("Hello, world!");
}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:.maldito-dot/workflow/action.yml
  build:.github/workflows/https://github.com/M1-Cal/Mandolin11/compare/monstro805-patch-1...Project

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
